name: Build
on: [push, pull_request]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Install additional build dependencies
        run: sudo apt-get install -yqq llvm lld
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: git clean -dxf && make -j$(nproc) CFLAGS_SRC="-Wall -Werror"
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dtbloader
          path: "build-*/dtbloader.*"
